### ISSUE TITLE
SassLinter doesn't allow for BEM formatted class patterns

### ISSUE THREAD

**Issue by kbeck303** [oomphinc/drupal-scaffold#18]
For now we have been adding `"selector-class-pattern": null` but I'm not sure turning this completely off is the best idea.

I found this thread/comment that provides one solution, but also links off to another project
https://github.com/postcss/postcss-bem-linter/issues/82#issuecomment-193851353

I think it's worth a conversation at the least, since BEM is a common practice.

**Comment by johncionci** [comment]
Quick follow up on this, here are some references that Im looking into:
https://stylelint.io/user-guide/faq/#how-should-i-lint-my-css-that-follows-a-bem-like-methodology
https://stylelint.io/user-guide/rules/selector-class-pattern/
https://github.com/simonsmith/stylelint-selector-bem-pattern

I've also asked @mattDesign to test this config rule.
```
"selector-class-pattern": ["^[a-z0-9\\-]+$", {
          "resolveNestedSelectors": true
        }]
```
but naturally that caused more errors than it fixed.

Its tough to nail down if this issue is because of the BEM style or because of the Nested Interpolation or a combination of the two.

**Comment by nathandentzau** [comment]
@johncionci where did you leave off with this?

**Comment by johncionci** [comment]
@nathandentzau gonna be something that I need time to test and review.

**Comment by raubin** [comment]
@johncionci - is still relevant and need attention?

**Comment by johncionci** [comment]
@raubin Im not sure how relevant this still is. I havent heard anyone complain about the issue which Im assuming is because they arent using BEM or it may have been resolved in newer updates. I have no issue closing this seeing as its been almost 2 years without any traction. Also, if in the future we are pushing to PostCSS probably not worth spending time on this.
