### ISSUE TITLE
Consider Adding Stage File Proxy Module

### ISSUE THREAD

**Issue by kclarkson** [oomphinc/drupal-scaffold#44]
Consider using the Stage File Proxy module for development.

This module allows us to use files stored on a production server so that our development environments do not have to download the files. 

https://support.acquia.com/hc/en-us/articles/360007322714-Serving-files-from-production-on-development-environments

**Comment by johnpicozzi** [comment]
@kclarkson - Thanks for posting this and showing interest in improving the Drupal Scaffold. We our currently working on the best way to maintain this project and working on a workflow for improvements like this. Please stay tuned and continue to open issues for items you would like to see. 

As a side note I personally struggle with this particular change because configuration would still need to be done after installing the Scaffold. The idea of the Scaffold (as it is right now) is that you can install it and get started quickly without much setup. The File Proxy module would require custom config for each project, that we couldn't include in the scaffold. So basically adding this would be running the composer command and leaving it in the code base for someone to enable and configure. I am more than willing to talk more about this once we finalize the maintenance and roadmap plans mentioned above. Thanks!

**Comment by kclarkson** [comment]
@johnpicozzi totally makes sense. I would think we could add configurations in the READ me files as well as comment out lines similar to the way pantheon provides you with starter files.
